### ISSUE TITLE
Error after some running test

### ISSUE THREAD

**Issue by MyNameIsDark01** [mastrHyperion98/crunchyroll-connect#2]
After running the program sometimes, I got an error where I should contact crunchyroll and my account seems locked (I can't login)

**Comment by mastrHyperion98** [comment]
Hello, 

I am aware of this issue. It would appear that Crunchyroll has some DDOS or rate limit protection. Essentially it times out your account for a while because it received too many requests. Typically login requests, from my experience. 

I actually have a fix for this in AmadeusTV. Ill roll it out here. Though I'm currently in vacation so it will be in a week or so.

**Comment by mastrHyperion98** [comment]
Updated with the aforementioned code^ sorry for delays.
